/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_Configuraciones_DatosBasicos;

import Metodos_Configuraciones.metodosDatosBasicos;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Carlos Valdez
 */
public class jpColoniaEjido extends javax.swing.JPanel {

    /**
     * Creates new form jpColoniaEjido
     */
    DefaultTableModel modelo;
    metodosDatosBasicos mdb;
    jdColoniaEjido jdC;
    Connection cn;

    public jpColoniaEjido(Connection c) {
        initComponents();

        cn = c;
        mdb = new metodosDatosBasicos(cn);
        modelo = (DefaultTableModel) tablaColonia.getModel();

        tablaColonia.setRowSorter(new TableRowSorter(modelo));

        llenaTablaColonia();
    }

    public void llenaTablaColonia() {
        limpiar(tablaColonia);
        mdb = new metodosDatosBasicos(cn);
        mdb.cargarInformacion2(modelo, 5, "select c.descripcion, l.Descripcion, m.Descripcion,e.descripcion, p.descripcion \n"
                + "from ejidocolonia c \n"
                + "inner join localidad l on (c.ID_Localidad=l.ID)\n"
                + "inner join municipio m on (l.ID_Municipio=m.ID)  \n"
                + "inner join estado e on (m.ID_Estado=e.ID) \n"
                + "inner join pais p on (e.ID_Pais=p.ID)\n"
                + "where c.ID_Situacion=1");
    }

    public void busquedaColonia() {
        String tipoC = "";
        String tipoL = "";
        String tipoM = "";
        String tipoE = "";
        String tipoP = "";
        String situacion = "";

        situacion = comboSituacionColonia.getSelectedItem() + "";

        if (situacion.equals("Inactivo")) {
            situacion = "2";
        } else if (situacion.equals("Activo")) {
            situacion = "1";
        }

        if (txtBusquedaC.getText().length() > 0) {
            tipoC = "AND c.descripcion like '" + txtBusquedaC.getText() + "%'";
        }
        if (txtBusquedaL.getText().length() > 0) {
            tipoL = "AND l.descripcion like '" + txtBusquedaL.getText() + "%'";
        }
        if (txtBusquedaM.getText().length() > 0) {
            tipoM = "AND m.descripcion like '" + txtBusquedaM.getText() + "%'";
        }
        if (txtBusquedaE.getText().length() > 0) {
            tipoE = "AND e.descripcion like '" + txtBusquedaE.getText() + "%'";
        }
        if (txtBusquedaP.getText().length() > 0) {
            tipoP = "AND p.descripcion like '" + txtBusquedaP.getText() + "%'";
        }

        String sql;
        if (situacion.equals("Todos")) {
            sql = "SELECT  c.Descripcion,l.descripcion, m.descripcion, e.descripcion, p.descripcion \n"
                    + "from ejidocolonia c \n"
                    + "inner join localidad l on (c.ID_Localidad=l.ID) \n"
                    + "inner join municipio m on (l.ID_Municipio=m.ID) \n"
                    + "inner join estado e on (m.ID_Estado=e.ID) \n"
                    + "inner join pais p on (e.ID_Pais=p.ID) \n"
                    + "where c.ID_Situacion <> 3 " + tipoC + " " + tipoL + " " + tipoM + " " + tipoE + " " + tipoP;
        } else {
            sql = "SELECT  c.Descripcion,l.descripcion, m.descripcion, e.descripcion, p.descripcion \n"
                    + "from ejidocolonia c \n"
                    + "inner join localidad l on (c.ID_Localidad=l.ID) \n"
                    + "inner join municipio m on (l.ID_Municipio=m.ID) \n"
                    + "inner join estado e on (m.ID_Estado=e.ID) \n"
                    + "inner join pais p on (e.ID_Pais=p.ID) \n"
                    + "where c.ID_Situacion=" + situacion + " " + tipoC + " " + tipoL + " " + tipoM + " " + tipoE + " " + tipoP;
        }
        limpiar(tablaColonia);
        mdb.cargarInformacion2(modelo, 5, sql);

    }

    private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBusquedaC = new javax.swing.JTextField();
        txtBusquedaL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBusquedaM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBusquedaE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBusquedaP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaColonia = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comboSituacionColonia = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(830, 570));

        jLabel6.setText("Colonia/Ejido");

        txtBusquedaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaCKeyReleased(evt);
            }
        });

        txtBusquedaL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaLKeyReleased(evt);
            }
        });

        jLabel7.setText("Localidad");

        txtBusquedaM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaMKeyReleased(evt);
            }
        });

        jLabel8.setText("Municipio");

        txtBusquedaE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaEKeyReleased(evt);
            }
        });

        jLabel9.setText("Estado");

        txtBusquedaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaPKeyReleased(evt);
            }
        });

        jLabel1.setText("País");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtBusquedaC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtBusquedaL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtBusquedaM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusquedaE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtBusquedaP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusquedaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusquedaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaColonia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Colonia/Ejido", "Localidad", "Municipio", "Estado", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaColonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaColoniaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaColonia);
        if (tablaColonia.getColumnModel().getColumnCount() > 0) {
            tablaColonia.getColumnModel().getColumn(0).setResizable(false);
            tablaColonia.getColumnModel().getColumn(1).setResizable(false);
            tablaColonia.getColumnModel().getColumn(2).setResizable(false);
            tablaColonia.getColumnModel().getColumn(3).setResizable(false);
            tablaColonia.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel10.setText("Situacion");

        comboSituacionColonia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Todos" }));
        comboSituacionColonia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSituacionColoniaItemStateChanged(evt);
            }
        });

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Desactivar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cerrar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSituacionColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(comboSituacionColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jdC = new jdColoniaEjido(null, true, "1", colonia, localidad, municipio, estado, pais, cn);
        jdC.jpC = this;
        jdC.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    String localidad = "", municipio = "", estado = "", pais = "", colonia = "";
    private void tablaColoniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaColoniaMouseClicked
        // TODO add your handling code here:
        colonia = modelo.getValueAt(tablaColonia.getSelectedRow(), 0) + "";
        localidad = modelo.getValueAt(tablaColonia.getSelectedRow(), 1) + "";  //Estado String
        municipio = modelo.getValueAt(tablaColonia.getSelectedRow(), 2) + "";
        estado = modelo.getValueAt(tablaColonia.getSelectedRow(), 3) + "";
        pais = modelo.getValueAt(tablaColonia.getSelectedRow(), 4) + "";

        if (evt.getClickCount() == 1) {
            System.out.println("1 Clic");
        }
        if (evt.getClickCount() == 2) {
            jdC = new jdColoniaEjido(null, true, "2", colonia, localidad, municipio, estado, pais, cn);
            jdC.jpC = this;
            jdC.setVisible(true);
        }
    }//GEN-LAST:event_tablaColoniaMouseClicked

    private void txtBusquedaCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaCKeyReleased
        // TODO add your handling code here:
        busquedaColonia();
    }//GEN-LAST:event_txtBusquedaCKeyReleased

    private void txtBusquedaLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaLKeyReleased
        // TODO add your handling code here:
        busquedaColonia();
    }//GEN-LAST:event_txtBusquedaLKeyReleased

    private void txtBusquedaMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaMKeyReleased
        // TODO add your handling code here:
        busquedaColonia();
    }//GEN-LAST:event_txtBusquedaMKeyReleased

    private void txtBusquedaEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaEKeyReleased
        // TODO add your handling code here:
        busquedaColonia();
    }//GEN-LAST:event_txtBusquedaEKeyReleased

    private void txtBusquedaPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPKeyReleased
        // TODO add your handling code here:
        busquedaColonia();
    }//GEN-LAST:event_txtBusquedaPKeyReleased

    private void comboSituacionColoniaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSituacionColoniaItemStateChanged
        // TODO add your handling code here:
        busquedaColonia();
    }//GEN-LAST:event_comboSituacionColoniaItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (colonia.equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione una colonia/ejido");
        } else {
            jdC = new jdColoniaEjido(null, true, "2", colonia, localidad, municipio, estado, pais, cn);
            jdC.jpC = this;
            jdC.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mdb.actualizarBasicos("UPDATE ejidocolonia SET ID_Situacion=2 where descripcion='" + colonia + "'");
        llenaTablaColonia();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboSituacionColonia;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaColonia;
    private javax.swing.JTextField txtBusquedaC;
    private javax.swing.JTextField txtBusquedaE;
    private javax.swing.JTextField txtBusquedaL;
    private javax.swing.JTextField txtBusquedaM;
    private javax.swing.JTextField txtBusquedaP;
    // End of variables declaration//GEN-END:variables
}
